name: "Renew Cloudflare Certificate"
description: "Checks if a certificate is available. If none is available or if the certificate expires within the next number of specified days it renews the certificate."
inputs:
  organization:
    description: "The organization"
    required: true
  cert-secret-name:
    description: "The name of the organizational level secret where to store the base64 encoded pfx file"
    required: true
  github-token:
    description: "A github token that has enough rights to read- and write organization level secrets"
    required: true
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.organization}}.
      shell: bash
    - run: ls -la
      shell: bash
    - run: goodbye.sh
      shell: bash
      # env:
      #   ORGANIZATION: ${{ inputs.organization }}
      #   CERT_SECRET_NAME: ${{ inputs.cert-secret-name }}
