name: "Renew certificates"
description: "Renew Cloudflare certificates"
inputs:
  organization:
    description: "Github Organization"
    required: true
runs:
  using: "composite"
  steps:
    - run: goodbye.sh
      shell: bash
