name: "Hello World"
description: "Greet someone"
inputs:
  organization: # id of input
    description: "Organization"
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash
