echo "ORGANIZATION=$ORGANIZATION"
echo "GITHUB_TOKEN=$GITHUB_TOKEN"
echo "CLOUDFLARE_API_KEY=$CLOUDFLARE_API_KEY"
echo "CERT_SECRET_NAME=$CERT_SECRET_NAME"
echo "CERT_PFX_BASE64=$CERT_PFX_BASE64"
echo "CERT_EMAIL=$CERT_EMAIL"
echo "CERT_PWD=$CERT_PWD"
echo "CERT_DOMAIN=$CERT_DOMAIN"
echo "CERT_STAGING=$CERT_STAGING"

if [[ $CERT_STAGING = true ]]
then
  echo "Issue staging certificate"
else
  echo "Issue production certificate"
fi
